verify dataplane.gobra
jcp19/VerifiedSCION pull request #45
Opened 2021-11-22 21:38 UTC by LinoTelschow

Changes:
-verify methods in dataplane.gobra

2021-11-24 10:29 UTC, jcp19 commented on gobra/lib/slayers/scion.gobra
> +func(s *SCION) getRawPktAccWithoutPreservePath(b []byte)
What do you mean by "without preserve path"? When is this desired?

2021-11-24 10:29 UTC, jcp19 commented on gobra/lib/slayers/path/scion/raw.gobra
> +// (tlino) added to speed up verification, this function deligates the IncPath call
typo, should be "delegates"

2021-11-24 10:29 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	// for d.running {
instead of rewriting like this, we can have a pure function that takes the DataPlane `d` as an argument and return `unfolding acc(DataPlaneMutexInvariant(d), _) in d.running` and just call this function here

2021-11-24 10:52 UTC, LinoTelschow commented on gobra/lib/slayers/scion.gobra
> +func(s *SCION) getRawPktAccWithoutPreservePath(b []byte)
In the updateSCIONLayer we need to access the rawPkt, but also need to guarantee that s.getgetRawScionPath() returns the same pointer after updateSCIONLayer terminates. For this purpose the `getRawPktAcc` method ensures that `s.getgetRawScionPath` returns the same pointer after the magic wand has been applied.

However, in other cases we don't need to preserve that `s.getgetRawScionPath` returns the same pointer after applying the magic wand. For these cases we can use `getRawPktAccWithoutPreservePath`

2021-11-24 10:53 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	// for d.running {
Agree!

2021-11-25 14:29 UTC, jcp19 commented on gobra/dependencies/gopacket/layers/bfd.gobra
> +// (tlino) Thus, we can give back access to the data slice
putting a reference to the discussion in the scion repository would be helpful for later reference here

2021-11-25 14:34 UTC, LinoTelschow commented on gobra/dependencies/gopacket/layers/bfd.gobra
> +// (tlino) Thus, we can give back access to the data slice
Sure!

2021-11-25 15:00 UTC, jcp19 commented on gobra/lib/slayers/scion.gobra
> +	verifyutils.BytesAcc(s.EmbeddedBaseLayer.Payload)
This is not sound. `s.EmbeddedBaseLayer.Payload` consists of a slice that may be aliased with other fields in a `SCION` structure. This can be seen in the method `(*SCION).DecodeFromBytes` in the lines
```go
s.Contents = data[:hdrBytes]
s.Payload = data[hdrBytes:]
```

2021-11-25 15:27 UTC, LinoTelschow commented on gobra/lib/slayers/scion.gobra
> +	verifyutils.BytesAcc(s.EmbeddedBaseLayer.Payload)
No, it should be ok.
If you look in the implementation of scion.DecodeFromBytes, you can see that data[hdrBytes:] isn't sub-sliced anywhere.

2021-11-25 16:50 UTC, jcp19 commented on gobra/lib/slayers/scion.gobra
> +	verifyutils.BytesAcc(s.EmbeddedBaseLayer.Payload)
Although that is true, you still use `data[CmnHdrLen:]` in the `DecodeFromBytes`, in the only call to `DecodeAddrHdr`

2021-11-25 17:14 UTC, LinoTelschow commented on gobra/lib/slayers/scion.gobra
> +	verifyutils.BytesAcc(s.EmbeddedBaseLayer.Payload)
yes, but if you check the DecodeAddrHdr, it only parses up to hdrBytes. However the DecodeAddrHdr doesn't specify this in it's contract, it just states that it needs permission to `data[CmnHdrLen:]` and doesn't give back access to the not parsed bytes.

2021-11-25 17:16 UTC, LinoTelschow commented on gobra/lib/slayers/scion.gobra
> +	verifyutils.BytesAcc(s.EmbeddedBaseLayer.Payload)
this can be a problem, since after `DecodeAddrHdr` the `Path.DecodeFromBytes` gets called on some suffix of `data`, but the access has been taken away from `DecodeAddrHdr`

2021-11-25 22:49 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +}
This method does not seem to modify the packet processor. Couldn't we just pass a fractional permission to `p.Mem()`, i.e., change the contract to
```
preserves acc(p.Mem(), 1/10)
```

2021-11-25 22:49 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) TODO: verify termination
this TODO can be removed, we already have the `decreases` annotation

2021-11-25 22:49 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) TODO: verify termination
Also has termination measure

2021-11-25 22:49 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	if _, ok :=( p.d.external)[egressID]; !ok {
typo

2021-11-25 22:49 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +ensures pr.Mem()
`p` does not seem to be modified here. Could we pass a fractional permission to `p.Mem()`?

2021-11-26 08:39 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	assume quoteLen <= len(p.origPacket)
it seems we don't need this assume

2021-11-26 16:09 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +ensures pr.Mem()
yes, but the call to packSCMP requires full permission

2021-11-26 16:09 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	assume p.path != nil
I might try that later

2021-12-01 18:18 UTC, LinoTelschow commented
Methods to check:
Verified:
- handleSCMPTraceRouteRequest
- handleSCMPTraceRouteRequest2
- validateEgressUp
- processOHP
- processOHP2
- getDummyMac
- getAddrAndRawPktAcc

partially verified:
- addEndhostPort

contracts only:
- processSCION
- process
- verifyCurrentMAC

2021-12-03 22:44 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	assume p != nil
are you sure about this? did you try replacing the `assume` with an `assert` to see if this works?

2021-12-03 22:54 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) Verified
this is not verfied, it does not contain a body. it is only specified

2021-12-03 22:57 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +func (pr processResult) getAddrAndRawPktAcc()
In general, comments describing these ghost operations should be well documented. In particular, it is important to know which memory locations might be aliased (e.g. `pr.OutAddr` and `pr.OutPkt`, right?)

2021-12-03 22:58 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) TODO: reverify
is this comment still valid?

2021-12-04 08:48 UTC, LinoTelschow commented on gobra/lib/slayers/scmp_msg.gobra
> +// }
Sure, I will comment them out!

2021-12-04 09:01 UTC, LinoTelschow commented on gobra/lib/slayers/scmp.gobra
> +}
We may do this. My first idea was to use only the Mem predicate.
But then I get problems with the `DecodeFromBytes` method. This method then needs to establish the Mem predicate. `DecodeFromBytes` then needs to reason about the `scn` field. In order to establish the Mem predicate, I may have to introduce a more restrictive precondition to `DecodeFromBytes`.

2021-12-04 09:28 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	assume p != nil
Yes, I first tried it with an assert. But Gobra cannot deduce that. Even-though gobra knows that p.path is not nil

2021-12-04 09:29 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) Verified
sure!

2021-12-07 17:41 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +func invalidDstAddr() (e error)
Yes, It is part of my fix for an issue I reported to the scion devs

2021-12-07 17:46 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	assume p.path != nil
The scionPacketProcessor already enforces that p.path != nil, together with that snippet:

```
p.path, ok = (p.scionLayer.Path).(*scion.Raw)
	if !ok {
		// TODO(lukedirtwalker) parameter problem invalid path?
		// (tlino) gobra doesn't support globals yet
		// return processResult{}, malformedPath
		fold p.scionLayer.Mem()
		pr, errRet = processResult{}, malformedPath()
		fold pr.Mem()
		return 
	}
```

Gobra should be able to deduce `p.path != nil`.
but it cannot. Thus I use the assume

2021-12-12 22:08 UTC, jcp19 reviewed
Checked until method `processPkt`

2021-12-13 08:23 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +}
Currently, I don't have better names. I splitted the predicates like this to distribute the forall assertions between the predicates in a fair way. I think these forall assertions are responsible for the overhead when a predicate is unfolded/folded.

2021-12-13 08:27 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		// d.Metrics.InputBytesTotal.With(inputLabels).Add(float64(p.N))
Yes, Im currently verifying this in the next PR

2021-12-13 08:28 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +// }
Nope, but I consider this function part of the next PR

2021-12-13 08:38 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +ensures (acc(pr.OutAddr.Mem(), 1/10) && acc(verifyutils.BytesAcc(pr.OutPkt), 1/10) && acc(pr.OutConn.Mem(), 1/1000)) --* pr.Mem()
The problem here is, I cannot provide an implementation for this function. A processResult has only access to the rawPkt. The OutAddr of the processResult contains a subslice of rawPkt. Furthermore, a processResult has only wildcard permission to OutConn (that's the problem we discussed on Friday, that we cannot have magic wands with wildcard permissions).
Thus, this function is there to give read access to these fields if it is needed. (The function is called before a send operation is called)

2021-12-13 08:41 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +ensures isZeroSCION(s)
yes, we need this. This is an invariant in the in the processBatch loop that calls this function

2021-12-13 08:45 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +ensures isZeroSCION(spkt)
yes, I can now start using the preserves keyword, I avoided it, since I wanted to avoid problems due to the ordering

2021-12-13 08:48 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +requires acc(DataPlaneMutexInvariant1(d), _) && acc(DataPlaneMutexInvariant2(d), _)
I also thought about that. But I'm not sure if it is really better to put the splitted invariant inside of `DataPlaneMutexInvariant`. This would then require more unfolding operations if `DataPlaneMutexInvariant1` or `DataPlaneMutexInvariant2` is needed.

2021-12-13 08:48 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +requires acc(DataPlaneMutexInvariant1(d), _) && acc(DataPlaneMutexInvariant2(d), _)
Or do you think I should try it?

2021-12-13 11:23 UTC, jcp19 reviewed
checked until menthod `validateIngressID`, inclusive

2021-12-13 11:23 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +decreases
This contract is a bit hard to read. Could we abstract the precondition in different predicates that group together permissions of the data-structures mentioned in this spec?

2021-12-13 11:23 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +decreases
PS: does not need to be pre-existing predicates, we can introduce new ones for this purpose

2021-12-13 11:23 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	assume p.path != nil
> Gobra should be able to deduce p.path != nil.

Why is that? Notice that nil might be the value of (p.scionLayer.Path).(*scion.Raw)

2021-12-13 11:23 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +ensures p.Mem()
Let`s use preserves. I won't repeat this comment but please address all instances of this pattern.

2021-12-13 13:31 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +}
If that is the case, why don't we just put the quantifiers inside predicates with a clear meaning (that is, the quantifier is the body of a new predicate, like in verifyutils.BytesAcc and put them inside DataPlaneMutexInvariant instead of splitting them arbitrarily in two predicates? My concern is that DataplaneMutexInvariant1 and DataplaneMutexInvariant2 do not form good abstractions and thus, it is hard to understand exactly what can be accessed when you have permissions to these predicates.

2021-12-13 13:34 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +requires acc(DataPlaneMutexInvariant1(d), _) && acc(DataPlaneMutexInvariant2(d), _)
It is not clear to me if the foldings and unfoldings of DataPlaneMutexInvariant would have a noticeable impact on performance because its body would be super simple. At the same time, I would first look into my comment above on DataPlaneMutexInvariant1 and DataPlaneMutexInvariant2 before trying this.

2021-12-13 13:36 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +ensures (acc(pr.OutAddr.Mem(), 1/10) && acc(verifyutils.BytesAcc(pr.OutPkt), 1/10) && acc(pr.OutConn.Mem(), 1/1000)) --* pr.Mem()
sure, but I would add a comment explaining this. This function is an assumption and all assumptions should be clearly identified for future reference and maintenance. What about my first question?

2021-12-13 13:39 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +}
Yes, that's a good idea!
This allows us to just use one predicate for the DataplaneMutexInvariant

2021-12-13 13:42 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +ensures isZeroSCION(s)
true, but at the same time, we have a call by value semantics - go copies the contents of the struct to this function. As such, the caller won't observe changes made to the copy of s passed to this function. Have you tried to verify the code without this postcondition?

2021-12-13 13:46 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +ensures (acc(pr.OutAddr.Mem(), 1/10) && acc(verifyutils.BytesAcc(pr.OutPkt), 1/10) && acc(pr.OutConn.Mem(), 1/1000)) --* pr.Mem()
"What about my first question?"
I will change the permission amounts, such we use the same amount for all

2021-12-13 13:47 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +ensures isZeroSCION(s)
not yet, but I will try that

2021-12-13 15:54 UTC, jcp19 reviewed
Checked until `handleSCMPTraceRouteRequest` exclusive

2021-12-13 15:54 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +ensures pr.Mem()
this is not super easy to read - isn't the postcondition when errRet != nil a weaker version of the `Mem` predicate of the scionPacketProcessor? If so, could we structure the Mem predicate to avoid this repetition here? (possibly with the use of new predicates)

2021-12-13 15:54 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) Verified
so much better :)

2021-12-13 15:54 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) verification does not terminate in a reasonable time after merge with master
does this comment still hold?

2021-12-13 21:26 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	(forall add net.Addr :: add in range(d.internalNextHops) ==> add.Mem()) &&
I think it makes more sense to keep this as it is. We only access these over an `acc(DataPlaneMutexInvariant(d), _)`
permission. In the changes of this PR we use a `BatchConnsAcc` predicate that inherits only wildcard permission when we access it over `acc(DataPlaneMutexInvariant(d), _)`.

2021-12-13 21:50 UTC, jcp19 requested changes

2021-12-13 21:50 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	assume p != nil
please look at an earlier comment about a similar point

2021-12-13 21:50 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +		}
this pattern can also be abstracted in a ghost function

2021-12-13 21:50 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) TODO d.svc not supported yet
invalid comment

2021-12-13 21:50 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +
shouldn't this include access to localIA.Mem()?

2021-12-13 21:50 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +func (s scmpPacker) prepareSCMP(scmpH *slayers.SCMP, scmpP gopacket.SerializableLayer,
I would add a comment describing the current status of this function - if you don't want to verify it, I would add in the comment the reasons why it is hard to verify this function for future reference.

2021-12-13 21:50 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +requires forall i int :: 0 <= i && i < len(quote) ==> acc(&quote[i])
If you do not plan to verify more code from this method, I would at least document the reasons why this function is so hard to verify. It would be useful for future reference.

2021-12-14 08:57 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +}
This predicate is established in the `parsPath` method. The context around the `parsePath` method has only half permission to some fields. And it makes sense to give some of this fields only partial permission, since we need to guarantee that these fields don't change. for example, we need to guarantee that p.rawPkt keeps pointing to the some location.

2021-12-14 09:28 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +decreases
I don't know if this really helps to improve readability. We then also have to introduce another such predicate for the process method. Then the reader has to look up two predicates to see how permissions are passed from `process` to `parsePath`

2021-12-14 09:48 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +decreases
True, but at the same time we could conceptually introduce a predicate per processing step - in each of these functions that are applied during processing, we would move the state of the scionPacketProcessor from one predicate to the other, which allows us to think of this as a transition system

2021-12-14 10:15 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +decreases
Yes, we might consider this option. But I would rather do this in the next PR, since we have quite a lot of changes already in this PR.
Would you agree with that?

2021-12-14 10:29 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	assume p.path != nil
"Gobra should be able to deduce p.path != nil"
yes, this claim isn't true.
But I think we cannot get rid of this assume

2021-12-14 10:37 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +ensures p.Mem()
Yes, this method is part of the next PR. Lets discuss it there!

2021-12-14 10:39 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) verification does not terminate in a reasonable time after merge with master
nope

2021-12-14 11:17 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +
no, there is no Mem() predicate for addr.IA

2021-12-14 11:20 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +requires forall i int :: 0 <= i && i < len(quote) ==> acc(&quote[i])
I want to verify that function, but in the next PR.

2021-12-14 11:35 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +func (s scmpPacker) prepareSCMP(scmpH *slayers.SCMP, scmpP gopacket.SerializableLayer,
I haven't completely given up verifying this method.
I think it is reasonable to assume that this method has not a high priority to get verified.
I have seen in Luca Halm's branch that he managed to verify the method, but he had to split it into 7 sub methods and he commented out some stuff like the panic calls. He also didn't had to pay attention to the aliasing issues with rawPkt and the long parsing and type checking times of the verifier.

2021-12-14 11:55 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	assume p.path != nil
Yes, but then it is unclear why this assumption is safe - assumptions should be used to overcome shortcommings of the tool - properties that we know to hold but that, for some reason, we are not able to prove them in Gobra. Right now, it is not clear that that is the case.

Maybe we can extend the Mem predicate of SCION to include the assertion `s.Path != nil`

2021-12-14 12:02 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	assume p.path != nil
"Maybe we can extend the Mem predicate of SCION to include the assertion s.Path != nil"
This assertion is already part of SCION.Mem()

2021-12-14 12:06 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +decreases
Not sure about that - as a reviewer, I am a bit concerned about merging this as it is because it is very easy to overlook details in this spec. However, if you insist on doing this in a later PR, please open an issue in this repository describing the task and mention this issue in a comment in this function.

2021-12-14 12:08 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +
Oops, my bad. I meant the `Mem` predicate of `internalIP`.

2021-12-14 13:07 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	assume p.path != nil
Maybe this is indeed a limitation of Gobra. I looked up again the behavior of these dynamic type assertions (https://go.dev/ref/spec#Type_assertions). 

The assert before the dynamic type assertion and a successful dynamic type assertions should imply that p.path != nil

```
	assert p.scionLayer.Path != nil
	p.path, ok = (p.scionLayer.Path).(*scion.Raw)
	if !ok {
		// TODO(lukedirtwalker) parameter problem invalid path?
		// (tlino) gobra doesn't support globals yet
		// return processResult{}, malformedPath
		fold p.scionLayer.Mem()
		pr, errRet = processResult{}, malformedPath()
		fold pr.Mem()
		return 
	}
	fold p.scionLayer.Mem()
	assert p.path == p.scionLayer.getRawScionPath()
	var err error

	// (tlino) we know that this holds, since (SCION).DecodeFromBytes has already decoded the path.
	// (tlino) a decoded path is always not nil and in this function of dynamic type *scion.Raw.
	// (tlino) however, (p.scionLayer.Path).(*scion.Raw) cannot deduce that p.path != nil.
	assume p.path != nil
```

2021-12-14 17:44 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		assert pr.Mem() --* (verifyutils.BytesAcc(rp))
Yes, I moved this to a ghost function

2021-12-14 17:47 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		}
Do you really think that's worth it?

Having just this block doesn't waste to much space and we can directly see how the magic wand is  implemented:

```
package pr.Mem() --* verifyutils.BytesAcc(rawPkt) {
	s.getRawPktAccWithoutPreservePath(rawPkt)
}
```

2021-12-14 18:07 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +		}
it depends on how often it occurs here and in other functions. Also, it looks redundant to have the assertion inside the package statement because any error caught by that assertion would also be caught by trying to package the wand

2021-12-14 18:12 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		}
yes, I removed the assertions already.

2021-12-14 18:14 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		}
There exists at least 3 different types of these `package pr.Mem() --* verifyutils.BytesAcc(rawPkt)`
blocks with slightly different implementations. introducing 3 different ghost functions for them might not always help the readability, since the reader then has to look up the implementation of these ghost functions

2021-12-14 23:07 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +decreases
Ok, I think I can try that in this PR. For this should I just introduce new predicates and reuse for them the body of the Mem predicate of the scionPacketProcessor?

```
pred (p *scionPacketProcessor) Mem() {
	acc(&p.d, _) &&
	acc(&p.ingressID, 1/4) &&
	acc(&p.rawPkt, 1/4) &&
	acc(&p.scionLayer, 1/4) &&
	acc(&p.origPacket, 1/4) &&
	acc(&p.buffer, 1/4) &&
	acc(&p.path) &&
	acc(&p.hopField) &&
	acc(&p.infoField) &&
	acc(&p.segmentChange) &&
	acc(DataPlaneMutexInvariant(p.d), _) &&
	verifyutils.BytesAcc(p.origPacket) &&
	acc(p.infoField) &&
	path.HopFieldInv(p.hopField) &&
	p.buffer.Mem() &&
	p.scionLayer != nil && p.scionLayer.Mem() &&
	cap(p.rawPkt) == bufSize &&
	p.path != nil && p.path == p.scionLayer.getRawScionPath() &&
 	p.rawPkt == p.scionLayer.getRawPkt()
}
```

Then we would end up with a lot predicates.
we may move these predicates to a new file to not overload the dataplane more
Do you think that's the way to do it?

2021-12-15 07:52 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +
internalIP is of type net.IP and this type has also no Mem() predicate

2021-12-15 10:06 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +
True. In another branch of Gobra, IP does have a Mem predicate whose body is the same as BytesAcc. If this IP is ever accessed, we should provide adequate permissions in this predicate

2021-12-15 10:18 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +
Yes when I verify the packSCMP2 method in the next PR, then I need to adapt this predicate.
So, I think it makes sense to change this in the next PR

2021-12-15 15:20 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +		msgs[i].N = 0
if there is no way to esablish this property without assuming it or without adding the code ourselves, might it be the case that the original code is buggy?

2021-12-15 15:22 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +// (tlino) We cannot give a wildcare permission amount to OutConn whithin a magic wand,
typo in "wildcard"

2021-12-15 15:52 UTC, jcp19 commented on gobra/lib/slayers/scmp.gobra
> +}
any updates on this?

2021-12-15 15:52 UTC, jcp19 commented on gobra/lib/slayers/scmp_msg.gobra
> +// }
any comments on this?

2021-12-15 18:21 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		msgs[i].N = 0
Yes, good point.
Maybe this method call here should be responsible to establish that property:
https://github.com/jcp19/VerifiedSCION/blob/a709234bd35ce186d3115a24588b479c5b626200/gobra/pkg/router/dataplane.gobra#L977

2021-12-16 18:29 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	assume len(updated) <= len(quote)
why do we have to assume this? Can't we somehow put a pre-condition here that ensures this?

2021-12-16 18:46 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	assume p != nil
how does it know that it is not nil here?

2021-12-16 18:49 UTC, jcp19 approved these changes

2021-12-16 18:49 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +		assume p != nil && p == s.getOHPPath()
can't we go without this assumption?

2021-12-16 20:18 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +	assume len(updated) <= len(quote)
I try to explain the problem:
https://github.com/jcp19/VerifiedSCION/blob/77cb34e63eb7cab49c79d1b1ab2204b81b6e3bfd/gobra/pkg/router/dataplane.gobra#L1730-L1752

At line 1730 we serialize the scion struct to a bytes array.
at line 1745 this byte array is stored in `updated`

The stuff from `updated` needs to be stored in the `quote` array
Note: `quote` is never larger than `updated`, since `updated` was obtained from the scion struct.
The scion struct was constructed from a subslice from `origPacket` and the scion struct doesn't change its length during the processing before.
Thus if we serialize it to `updated` it shouldn't be longer than the `quote` slice.

However, we have no trivial way to constrain that `Bytes()`method at line 1745 can guarantee that constraint on the length.
Thus I used the assume here

2021-12-16 20:24 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		assume p != nil && p == s.getOHPPath()
I can try to change the post condition of `updateSCIONLayer`

2021-12-16 20:40 UTC, jcp19 commented on gobra/pkg/router/dataplane.gobra
> +	assume len(updated) <= len(quote)
Ah I see. We could probably introduce a stronger specification for the Bytes method via some ghost-state but, as it stands, this is fine

2021-12-16 21:19 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		assume p != nil && p == s.getOHPPath()
The problem here is I somehow need to relate p with (s.Path).(*onehop.Path)

2021-12-16 21:21 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		assume p != nil && p == s.getOHPPath()
I think there isn't really a nice solution for that:
https://github.com/jcp19/VerifiedSCION/blob/77cb34e63eb7cab49c79d1b1ab2204b81b6e3bfd/gobra/pkg/router/dataplane.gobra#L3061-L3148

As you can see on line 3078 we established this relation

2021-12-16 21:22 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		assume p != nil && p == s.getOHPPath()
However, when we fold that thing at line 3134 and perform the updateSCIONLayer stuff then we have lost that relation

2021-12-16 21:47 UTC, LinoTelschow commented on gobra/pkg/router/dataplane.gobra
> +		assume p != nil && p == s.getOHPPath()
Ok, I think I found a solution for that!

2021-12-17 09:21 UTC, merged